apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-2bsj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-oucx-tenant/rhtap-demo-app/hacbs-test-project-2bsj@sha256:18db30edded1e1d5e8d44eb021450ecd581de1869f6691664fe450b80a055ddd
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
