apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-2bsj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-oucx-tenant/rhtap-demo-app/hacbs-test-project-2bsj@sha256:8b18f2079473efbfce8dd5e63690f0f64009bdee4ac1465e802f60cc5609c642
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
